### ISSUE TITLE
IndexOutOfRangeException thrown when extracting.

### ISSUE THREAD

**Issue by pbone64** [Lomeli12/TBLEditor#1]
An `IndexOutOfRangeException` is thrown by `mergeCharBytesIntoShort` when extracting a .TBL file. This has been confirmed on both TBLEditorWin (downloaded from releases) and TBLEditorCore (built from source because of some dependency shenanigans).
```
[01:35:35][TBLEditor][INFO]: Starting TBLEditor
[01:35:35][TBLEditor][INFO]: Reading C:\Users\pbone\Documents\Tools\TBLEditorWin\EQUIPITEMTABLE.TBL to decompile...
[01:35:35][TBLEditor][INFO]: Table Size: 25345

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TBLLib.NameTable.mergeCharBytesIntoShort(Byte[] table, Int32 leftByteIndex)
   at TBLLib.NameTable.readBytes(Byte[] tableData)
   at TBLLib.NameTable.fromFile(String path, Logger log)
   at TBLEditor.Program.Main(String[] args)
```

I realize that this is probably calling into the void of an abandoned project but I might as well try.

**Comment by pbone64** [comment]
I should note that these tables are extracted from Etrian Odyssey V instead of pq2 though they should both use the same (or similar) .TBL format. I have not tested a tbl file from pq2 as I do not have access to data from it, but I can try to obtain it if need be.

**Comment by Lomeli12** [comment]
I remember when I was basing this off [SkillEdit](https://github.com/ReaTsukuda/SkillEdit), which was made for Etrian Odyseey III, there were some very slight differences that I needed to work around. Since EOV came out between EOIII and PQ2, it's likely some, but not all, of the changes that happened to the PQ2 version of the format were not there for EOV, causing this issue. I seem to recall PQ1 tbl files not working with my tool, but it's been a while so I might be misremembering. I'd have to actually look at a tbl file from EOV and compare it to a PQ2 tbl file via a hex editor, which is a process as you can imagine and something I'd have to relearn since I haven't touched this project in a while. 

Since I'm not actively working on this project, I'm just gonna close this for now. However, if I ever get the drive again to work on it again, I might look into adding support for EOV and maybe other EO games/PQ1. Might also be a good idea to look at [SkillEdit](https://github.com/ReaTsukuda/SkillEdit) and hope it might work with EOV tbls. If it doesn't but you're willing to spend the time in a hex editor, you can also use it as a base to make a EOV specific tool of your own, using TBLEditor as a reference for any additional changes.

**Comment by pbone64** [comment]
Sounds good. Thanks for the response!
